export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_IP_ADDRESS = 'GET_IP_ADDRESS';
export const GET_LOGGEDIN_USER = 'GET_LOGGEDIN_USER'
export const SET_LOADING = 'SET_LOADING';